// Package the backend: PyInstaller produces a standalone binary (release/backend/lite-work-backend)
// Cross-platform: adapts venv paths and the --add-data separator for Windows / macOS / Linux.
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const isWindows = process.platform === "win32";
const python = isWindows
  ? path.join(root, ".venv", "Scripts", "python.exe")
  : path.join(root, ".venv", "bin", "python");
const outDir = path.join(root, "release", "backend");
const clean = process.argv.includes("--clean") || process.env.LITEWORK_PYINSTALLER_CLEAN === "1";

if (!fs.existsSync(python)) {
  console.error(
    isWindows
      ? "[package] .venv\\Scripts\\python.exe not found. Run first: python -m venv .venv && .venv\\Scripts\\pip install -e ."
      : "[package] .venv/bin/python not found. Run first: python3 -m venv .venv && .venv/bin/pip install -e ."
  );
  process.exit(1);
}

fs.mkdirSync(outDir, { recursive: true });
// 只清理最终 onedir 输出，保留 release/_build 的分析缓存。
// 否则 PyInstaller 增量收集时可能与旧的 Python.framework 链接冲突。
fs.rmSync(path.join(outDir, "lite-work-backend"), { recursive: true, force: true });

const webDist = path.join(root, "web", "dist");
if (!fs.existsSync(path.join(webDist, "index.html"))) {
  console.error("[package] web/dist not found. Run first: npm run build:web");
  process.exit(1);
}

// 图表引擎随安装包分发：在技能目录下安装 node_modules（@plantuml/core /
// @resvg/resvg-js / @mermaid-js/mermaid-cli），随 --add-data skills 一起
// 打进 _internal/skills/——用户装完应用即离线可渲染，无需首次启动联网装。
// PUPPETEER_SKIP_DOWNLOAD：chromium（300MB+）不打包，运行时用系统 Chrome。
const diagramSkillDir = path.join(root, "skills", "diagram-to-office");
const localCorePkg = path.join(diagramSkillDir, "node_modules", "@plantuml", "core");
if (process.env.LITEWORK_SKIP_SKILL_ENGINES === "1") {
  console.log("[package] 跳过技能引擎安装（LITEWORK_SKIP_SKILL_ENGINES=1）");
} else if (fs.existsSync(localCorePkg)) {
  console.log("[package] 技能引擎 node_modules 已存在，跳过安装");
} else {
  console.log("[package] 安装图表引擎到技能目录（随安装包分发）...");
  execSync("npm install --no-audit --no-fund", {
    cwd: diagramSkillDir,
    stdio: "inherit",
    env: { ...process.env, PUPPETEER_SKIP_DOWNLOAD: "1" },
  });
}

// 技能解释器随安装包分发：python-build-standalone 的独立 CPython。
// 技能脚本优先用它执行（litework/app.py 把它的 bin 前置进子进程 PATH），并通过
// 其 site-packages/sitecustomize.py 把 _internal（PyInstaller 收集的 PyYAML /
// pymupdf / python-docx / openpyxl / python-pptx / lxml / Pillow）追加进
// sys.path —— 用户装完即离线可用，与系统 Python 是否安装、什么版本都无关。
const PY_VER = "3.14.7";
const PY_TAG = "20260901";
const PY_MINOR = PY_VER.split(".").slice(0, 2).join("."); // 3.14
const skillPyCache = path.join(root, "release", "skill-python");

const SITECUSTOMIZE_SRC = `# Generated by lite-work build (scripts/package-backend.mjs).
# Append the packaged _internal (PyInstaller-collected third-party packages) to
# sys.path so skill scripts can import PyYAML/pymupdf/python-docx/... offline.
import os as _os
import sys as _sys


def _is_internal(d):
    return bool(d) and _os.path.isdir(_os.path.join(d, "skills")) \\
        and _os.path.isdir(_os.path.join(d, "pymupdf"))


_found = None
_d = _os.path.dirname(_os.path.abspath(__file__))
for _ in range(12):
    _parent = _os.path.dirname(_d)
    if not _parent or _parent == _d:
        break
    _d = _parent
    if _is_internal(_d):
        _found = _d
        break
    # 开发态：release/skill-python/python/... → release/backend/lite-work-backend/_internal
    _dev = _os.path.join(_d, "backend", "lite-work-backend", "_internal")
    if _is_internal(_dev):
        _found = _dev
        break

if _found and _found not in _sys.path:
    _sys.path.append(_found)
`;

function skillPythonAsset() {
  const archName = { arm64: "aarch64", x64: "x86_64" }[process.arch] || process.arch;
  if (isWindows) return `cpython-${PY_VER}+${PY_TAG}-${archName}-pc-windows-msvc-install_only.tar.gz`;
  if (process.platform === "darwin") return `cpython-${PY_VER}+${PY_TAG}-${archName}-apple-darwin-install_only.tar.gz`;
  return `cpython-${PY_VER}+${PY_TAG}-${archName}-unknown-linux-gnu-install_only.tar.gz`;
}

function prepareSkillPython() {
  const pyRoot = path.join(skillPyCache, "python");
  const marker = isWindows
    ? path.join(pyRoot, "python.exe")
    : path.join(pyRoot, "bin", "python3");
  if (!fs.existsSync(marker)) {
    fs.mkdirSync(skillPyCache, { recursive: true });
    const asset = skillPythonAsset();
    const tarball = path.join(skillPyCache, asset);
    if (!fs.existsSync(tarball)) {
      // GitHub 在部分网络不可达：直连失败后依次尝试国内反代
      const rel = `astral-sh/python-build-standalone/releases/download/${PY_TAG}/${asset}`.replace(/\+/g, "%2B");
      const mirrors = ["", "https://ghfast.top/", "https://gh-proxy.com/", "https://ghproxy.net/"];
      let lastErr = null;
      for (const base of mirrors) {
        const url = base ? `${base}https://github.com/${rel}` : `https://github.com/${rel}`;
        try {
          console.log(`[package] 下载技能解释器: ${url}`);
          execSync(`curl -fL --retry 2 --connect-timeout 15 -o "${tarball}.part" "${url}"`, { stdio: "inherit" });
          fs.renameSync(`${tarball}.part`, tarball);
          lastErr = null;
          break;
        } catch (err) {
          lastErr = err;
          console.log("[package] 该源失败，尝试下一个 ...");
        }
      }
      if (lastErr) throw lastErr;
    }
    console.log("[package] 解包技能解释器 ...");
    fs.rmSync(pyRoot, { recursive: true, force: true });
    execSync(`tar -xzf "${tarball}" -C "${skillPyCache}"`, { stdio: "inherit" });
  }
  // 精简：技能用不到的标准库大块（保留 pip 之外的运行必需部分）
  for (const rel of ["test", "idlelib", "tkinter", "ensurepip", "pydoc_data", "lib2to3"]) {
    fs.rmSync(path.join(pyRoot, "lib", `python${PY_MINOR}`, rel), { recursive: true, force: true });
  }
  const spDir = isWindows
    ? path.join(pyRoot, "Lib", "site-packages")
    : path.join(pyRoot, "lib", `python${PY_MINOR}`, "site-packages");
  fs.mkdirSync(spDir, { recursive: true });
  fs.writeFileSync(path.join(spDir, "sitecustomize.py"), SITECUSTOMIZE_SRC, "utf-8");

  // 单文件依赖：PyInstaller 把 <name>.py 收进 PYZ，不会落到 _internal，外部解释器
  // 读不到 —— 直接从构建 venv 拷进随包解释器的 site-packages。
  const venvSite = isWindows
    ? path.join(root, ".venv", "Lib", "site-packages")
    : path.join(root, ".venv", "lib", `python${PY_MINOR}`, "site-packages");
  for (const name of ["typing_extensions", "six"]) {
    const src = path.join(venvSite, `${name}.py`);
    const dst = path.join(spDir, `${name}.py`);
    if (fs.existsSync(src) && !fs.existsSync(dst)) {
      fs.copyFileSync(src, dst);
      console.log(`[package] 单文件依赖入包: ${name}.py`);
    }
  }
  return pyRoot;
}

const skillPyRoot = prepareSkillPython();
console.log(`[package] 技能解释器: ${skillPyRoot}`);

// Windows uses ';', macOS/Linux use ':'
const sep = isWindows ? ";" : ":";

const specArgs = [
  "--noconfirm",
  ...(clean ? ["--clean"] : []),
  "--onedir",
  "--name", "lite-work-backend",
  "--distpath", outDir,
  "--workpath", path.join(root, "release", "_build"),
  "--specpath", path.join(root, "release", "_spec"),
  "--paths", root,
  "--add-data", `${webDist}${sep}web${path.sep}dist`,
  "--add-data", `${path.join(root, "skills")}${sep}skills`,
  "--add-data", `${skillPyRoot}${sep}skill-python`,
  "--add-data", `${path.join(root, "litework", "builtin_plugins")}${sep}litework${path.sep}builtin_plugins`,
  "--collect-all", "fastapi",
  "--collect-all", "uvicorn",
  "--collect-all", "starlette",
  "--collect-submodules", "httpx",
  "--collect-all", "tree_sitter",
  "--collect-all", "tree_sitter_typescript",
  "--collect-all", "tree_sitter_java",
  "--collect-all", "tree_sitter_go",
  "--collect-submodules", "pathspec",
  "--collect-submodules", "litework",
  "--collect-all", "pydantic",
  "--collect-all", "rapidocr_onnxruntime",
  "--collect-all", "onnxruntime",
  "--collect-all", "cv2",
  // 技能运行时依赖（academic-paper-engineering / document-styling 等）：
  // 随包收集后，随包技能解释器（skill-python，见上）离线即可 import。
  // 注意必须用 --collect-all：--collect-submodules 只把 .so/data 落到 _internal，
  // Python 源码留在 PYZ 里，外部解释器（skill-python）读到的是没有 __init__ 的空壳。
  "--collect-all", "pymupdf",
  "--collect-all", "fitz",
  "--collect-all", "yaml",
  "--collect-all", "docx",
  "--collect-all", "pptx",
  "--collect-all", "lxml",
  "--collect-all", "PIL",
  "--collect-all", "openpyxl",
  "--collect-all", "et_xmlfile",
  "--collect-all", "xlsxwriter",
  "--collect-all", "numpy",
  "--collect-all", "pandas",
  "--collect-all", "dateutil",
  "--collect-all", "typing_extensions",
  "--collect-all", "defusedxml",
  "--collect-all", "reportlab",
  "--collect-all", "latex2mathml",
  "--collect-all", "mammoth",
  // playwright：专利技能的 mermaid 出图 + CNIPA 检索。包内 driver/ 含平台 node
  // 可执行（130M 级），--collect-all 一并收入 _internal；greenlet 为 C 扩展、
  // pyee 为纯 Python 依赖，缺一个技能脚本 import playwright 都会挂，必须一起收。
  "--collect-all", "playwright",
  "--collect-all", "pyee",
  "--collect-all", "greenlet",
  "--collect-all", "curl_cffi",
  "--hidden-import", "uvicorn.logging",
  "--hidden-import", "uvicorn.loops",
  "--hidden-import", "uvicorn.loops.auto",
  "--hidden-import", "uvicorn.protocols",
  "--hidden-import", "uvicorn.protocols.http",
  "--hidden-import", "uvicorn.protocols.http.auto",
  "--hidden-import", "uvicorn.protocols.websockets",
  "--hidden-import", "uvicorn.protocols.websockets.auto",
  "--hidden-import", "uvicorn.lifespan",
  "--hidden-import", "uvicorn.lifespan.on",
  path.join(root, "litework_entry.py"),
];

console.log("[package] Packaging backend with PyInstaller...");
console.log(`  python: ${python}`);
console.log(`  output: ${outDir}/lite-work-backend/ (--onedir, faster than onefile)`);
console.log(`  mode: --onedir${clean ? " --clean" : " (incremental cache)"}`);
const startedAt = Date.now();
execSync([python, "-m", "PyInstaller", ...specArgs].join(" "), {
  cwd: root,
  stdio: "inherit",
  env: { ...process.env, PYTHONPATH: root },
});
console.log(`  elapsed: ${((Date.now() - startedAt) / 1000).toFixed(1)}s`);

const outDirName = isWindows ? "lite-work-backend.exe" : "lite-work-backend";
const binary = path.join(outDir, "lite-work-backend", outDirName);
if (!fs.existsSync(binary)) {
  console.error("[package] Backend packaging failed: binary was not generated");
  process.exit(1);
}
console.log(`[package] Backend binary: ${binary}`);

// 清理第三方包自带的测试/缓存（PyInstaller --collect-all 会把 numpy/pandas 等
// 的 tests/ 一并收入 _internal——运行时用不到，纯冗余体积）。只清第三方，不碰
// litework 自己的产物（litework 的测试本就不在收集范围内）。
const internalDir = path.join(outDir, "lite-work-backend", "_internal");
if (fs.existsSync(internalDir)) {
  let removedFiles = 0, removedDirs = 0;
  const walk = (dir) => {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) {
        if (e.name === "__pycache__" || e.name === "tests" || e.name === "test") {
          fs.rmSync(p, { recursive: true, force: true });
          removedDirs++;
        } else {
          walk(p);
        }
      } else if (e.name.startsWith("test_") && e.name.endsWith(".py")) {
        fs.rmSync(p, { force: true });
        removedFiles++;
      } else if (e.name === "conftest.py") {
        fs.rmSync(p, { force: true });
        removedFiles++;
      }
    }
  };
  walk(internalDir);
  console.log(`[package] 清理第三方 tests/__pycache__: ${removedDirs} 目录, ${removedFiles} 文件`);
}
